import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef } from "react";
import { PublicKey, Keypair, Connection, clusterApiUrl } from "@solana/web3.js";
import { encodeURL, createQR, findReference } from '@solana/pay';
import BigNumber from 'bignumber.js';

export default function Home() {
  const qrRef = useRef(null);

  const recipient = new PublicKey('2sCbjskDpdT8P7K1uFkCwsRVF8q1YSPzDepqdkgkYdD9');
  const reference = new Keypair().publicKey;
  const amount = 0;
  // const amount = new BigNumber(0.5);
  const label = 'My little store';
  const message = 'You Bought Some Goodies';

  const solana_pay_url = encodeURL({ recipient, amount, reference, label, message });

  useEffect(() => {
    const qr = createQR(solana_pay_url, 360, 'white', 'black');
    if (qrRef.current) {
      qrRef.current.innerHTML = '';
      qr.append(qrRef.current);
      console.log("appended");
    }
  }, [solana_pay_url]);

  const connection = new Connection(clusterApiUrl('devnet'), 'confirmed');
  const intervalRef = useRef(null);

  useEffect(() => {
    const checkPaymentStatus = async () => {
      try {
        const signatureInfo = await findReference(connection, reference, { finality: 'confirmed' });
        if (signatureInfo) {
          console.log("Payment confirmed:", signatureInfo);
          clearInterval(intervalRef.current); 
          alert("Payment confirmed successfully!");
        }
      } catch (error) {
        console.error("Error checking payment status:", error);
      }
    };

    intervalRef.current = setInterval(checkPaymentStatus, 5000);

    return () => clearInterval(intervalRef.current);
  }, [connection, reference]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <br />
        <h2 className={styles.center}>Scan the QR code to pay</h2>
        <div className={styles.center} ref={qrRef}></div>
      </main>
    </>
  );
}